### ISSUE TITLE
Developer rating enhancement 

### ISSUE THREAD

**Issue by Domieck** [tunga-io/tunga-web#160]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[X] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

The architecture for rating developers is in place. However, we still expect clients to go over it manually, as in: they go the platform and leave a rating behind.

## Expected behavior

As soon as a task is finished and payment is being finalized, I'd like a pop up to appear with to the profile of the the developer on the left and an easy rating system on the right. The rating system consists of a rating option as we know it: from 1 to 5 stars. Below this is a small text field where a client can choose (so this is optional, not mandatory) to leave a few comments behind. 

The text above the star rating should be: How would you rate this developer? 

The text above the text field should: Is there anything you would like to say about the developer?

## Please tell us about your environment (optional for feature requests)

<pre><code>

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
- [ ] Other version XX 

Operating System:
- [ ] macOS version XX
- [ ] Windows version XX
- [ ] Linux  XX
- [ ] Android version XX
- [ ] iOS version XX
- [ ] Windows Phone version XX
- [ ] Other version XX 

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

For Developer issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by davidsemakula** [comment]
@Domieck so this is what already exists and the client is automatically redirected here after they make a payment

<img width="708" alt="screen shot 2017-07-12 at 16 23 01" src="https://user-images.githubusercontent.com/7472843/28119732-92078ea0-671e-11e7-8344-c1ea6dda1d9e.png">

I can make out that you want to add an option for comment and showing the developer's profile
The latter should probably be profiles as there's potential for collaboration

1) how much of the profile would you propose to be shown (Just image and name? probably better in case of multiples)
2) are you proposing a reduction in the attributes to rated on (currently 3 as per image) to just one rating?
> The rating system consists of a rating option as we know it: from 1 to 5 stars

3) In terms of flow, you seemed to indicate a change from current implementation, but from the proposal only change seems to be proposing a pop up instead of a dedicated page as shown below
<img width="666" alt="screen shot 2017-07-12 at 16 34 42" src="https://user-images.githubusercontent.com/7472843/28120239-1af2deee-6720-11e7-9508-6a9bdbc5849c.png">

Let me know if I'm missing something, especially about the pop up and the triggers for showing it.

**Comment by Domieck** [comment]
Thank you for the quick feedback @davidsemakula 

We can continue with both the three attributes to rate and the being forwarded to a page dedicated to this. However, I think this should before paying perhaps; it forces the client more to actually fill it (Hence why I proposed the pop up on the client screen instead of forwarding them afterwards).

Concerning how the profiles should be shown, I'd say to go indeed with option one. Above the profiles on the right, it could say "You've worked with:" and then the profiles below.

There are too small mistakes in the text. Time is missing: "Please take 5 seconds of your **time** to rate our developer(s). Thank you!" In advance isn't used much in English.

Also, I'd suggest using: "We would appreciate it if you could take a moment to rate our developer(s)." Sounds less demanding IMO. In that case, the first sentence could be something like "Rating developers help the Tunga developer community a great deal." WDYT?
